services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_web
    ports:
      - '3101:3101'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3101}
      NODE_ENV: production
      WHATSAPP_NUMBER: ${WHATSAPP_NUMBER}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - solar_net

  db:
    image: postgres:16-alpine
    container_name: solar_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - solar_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - solar_net

volumes:
  solar_pgdata:
    driver: local

networks:
  solar_net:
    driver: bridge
